services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: nimda
      MYSQL_DATABASE: utip_dam
      MYSQL_USER: example_db_user
      MYSQL_PASSWORD: example_db_pass
    volumes:
      - ./cluster/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  webapp:
    image: janineson/utipdam_tomcat:latest
    volumes:
      - ./cluster/data:/data
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl -Is localhost:8080/mobility | head -n 1 | grep 302 || exit 1
      timeout: 20s
      retries: 10
    links:
      - db

  portal:
    image: janineson/utipdam_nginx:latest
    depends_on:
      webapp:
        condition: service_healthy
    ports:
      - '8888:80'
    links:
      - webapp:tomcat1
