services:
  portal:
    image: nginx:stable-alpine
    ports:
      - '8888:80'
    volumes:
      - ./cluster/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - webapp:tomcat1

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: nimda
      MYSQL_DATABASE: utip_dam
      MYSQL_USER: example_db_user
      MYSQL_PASSWORD: example_db_pass
    volumes:
      - ./cluster/db:/docker-entrypoint-initdb.d

  webapp:
    build: ./cluster/tomcat
    volumes:
      - ./cluster/data:/data
      - ./cluster/tomcat/webapps/mobility.war:/usr/local/tomcat/webapps/mobility.war
    links:
      - db
